// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogPostDocumentDataSlicesSlice =
  | HeroSlice
  | TextBlockSlice
  | ListingIndexSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date Published field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.date_published
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_published: prismic.DateField;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type BuycommercialDocumentDataSlicesSlice =
  | TextBlockSlice
  | ProductInfoSlice
  | PropertiesSlice
  | TestimonialsSlice
  | StatsSliceSlice
  | HeroSlice
  | FeaturedEstatesSlice
  | OurTeamSlice
  | FollowUsSlice
  | BlogIndexSlice
  | PartnersSlice
  | ConnectSlice
  | ContactFormSliceSlice
  | NewsIndexSlice;

/**
 * Content for BuyCommercial documents
 */
interface BuycommercialDocumentData {
  /**
   * Slice Zone field in *BuyCommercial*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: buycommercial.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BuycommercialDocumentDataSlicesSlice> /**
   * Meta Title field in *BuyCommercial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: buycommercial.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *BuyCommercial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: buycommercial.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *BuyCommercial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: buycommercial.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * BuyCommercial document from Prismic
 *
 * - **API ID**: `buycommercial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BuycommercialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BuycommercialDocumentData>,
    "buycommercial",
    Lang
  >;

type BuyresidentialDocumentDataSlicesSlice =
  | FollowUsSlice
  | FeaturedEstatesSlice
  | OurTeamSlice
  | ConnectSlice
  | HeroSlice
  | StatsSliceSlice
  | TestimonialsSlice
  | ProductInfoSlice
  | TextBlockSlice
  | PropertiesSlice;

/**
 * Content for BuyResidential documents
 */
interface BuyresidentialDocumentData {
  /**
   * Slice Zone field in *BuyResidential*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: buyresidential.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BuyresidentialDocumentDataSlicesSlice> /**
   * Meta Title field in *BuyResidential*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: buyresidential.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *BuyResidential*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: buyresidential.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *BuyResidential*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: buyresidential.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * BuyResidential document from Prismic
 *
 * - **API ID**: `buyresidential`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BuyresidentialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BuyresidentialDocumentData>,
    "buyresidential",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | BlogIndexSlice
  | ProductInfoSlice
  | ConnectSlice
  | FollowUsSlice
  | PropertiesSlice
  | PartnersSlice
  | HighlightSlice
  | TestimonialsSlice
  | HeroSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type NewsDocumentDataSlicesSlice =
  | FollowUsSlice
  | ListingIndexSlice
  | HeroSlice
  | ConnectSlice
  | TextBlockSlice;

/**
 * Content for News documents
 */
interface NewsDocumentData {
  /**
   * Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date Published field in *News*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: news.date_published
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_published: prismic.DateField;

  /**
   * Featured Image field in *News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *News*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsDocumentDataSlicesSlice> /**
   * Meta Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;

type PageDocumentDataSlicesSlice =
  | NewsIndexSlice
  | TextBlockSlice
  | ListingIndexSlice
  | FeaturedEstatesSlice
  | StatsSliceSlice
  | ContactFormSliceSlice
  | OurTeamSlice
  | ProductInfoSlice
  | PropertiesSlice
  | HighlightSlice
  | FollowUsSlice
  | TestimonialsSlice
  | HeroSlice
  | ConnectSlice
  | PartnersSlice
  | BlogIndexSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PropertyDocumentDataSlicesSlice = never;

/**
 * Content for Property documents
 */
interface PropertyDocumentData {
  /**
   * Property Title field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.property_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  property_title: prismic.KeyTextField;

  /**
   * Sub Heading field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.sub_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Construction Status field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.construction_status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  construction_status: prismic.KeyTextField;

  /**
   * Ownership field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.ownership
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ownership: prismic.KeyTextField;

  /**
   * Location field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Price Square Ft field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.price_square_ft
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price_square_ft: prismic.KeyTextField;

  /**
   * Super Built Area field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.super_built_area
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  super_built_area: prismic.KeyTextField;

  /**
   * Floor field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.floor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  floor: prismic.KeyTextField;

  /**
   * Tagline field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Property Image field in *Property*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: property.property_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  property_image: prismic.ImageField<never>;

  /**
   * Property Type field in *Property*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: property.property_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  property_type: prismic.SelectField<"Residential " | "Commercial">;

  /**
   * Listing Type field in *Property*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: property.listing_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  listing_type: prismic.SelectField<"Buy " | "Rent">;

  /**
   * Route Name field in *Property*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: property.route_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  route_name: prismic.ContentRelationshipField<
    "buyresidential" | "rent_commercial" | "rent_residential" | "buycommercial"
  >;

  /**
   * Slice Zone field in *Property*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: property.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PropertyDocumentDataSlicesSlice> /**
   * Meta Title field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: property.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: property.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Property*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: property.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Property document from Prismic
 *
 * - **API ID**: `property`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PropertyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PropertyDocumentData>,
    "property",
    Lang
  >;

type RentCommercialDocumentDataSlicesSlice =
  | PropertiesSlice
  | TestimonialsSlice
  | HighlightSlice
  | TextBlockSlice
  | StatsSliceSlice
  | ProductInfoSlice
  | HeroSlice
  | FeaturedEstatesSlice
  | OurTeamSlice
  | PartnersSlice
  | BlogIndexSlice
  | FollowUsSlice
  | ConnectSlice
  | ContactFormSliceSlice;

/**
 * Content for Rent Commercial documents
 */
interface RentCommercialDocumentData {
  /**
   * Slice Zone field in *Rent Commercial*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rent_commercial.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RentCommercialDocumentDataSlicesSlice> /**
   * Meta Title field in *Rent Commercial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: rent_commercial.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Rent Commercial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: rent_commercial.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Rent Commercial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rent_commercial.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Rent Commercial document from Prismic
 *
 * - **API ID**: `rent_commercial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RentCommercialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RentCommercialDocumentData>,
    "rent_commercial",
    Lang
  >;

type RentResidentialDocumentDataSlicesSlice =
  | TestimonialsSlice
  | HighlightSlice
  | ProductInfoSlice
  | StatsSliceSlice
  | TextBlockSlice
  | HeroSlice
  | OurTeamSlice
  | PartnersSlice
  | BlogIndexSlice
  | FollowUsSlice
  | ConnectSlice
  | ContactFormSliceSlice
  | NewsIndexSlice;

/**
 * Content for Rent Residential documents
 */
interface RentResidentialDocumentData {
  /**
   * Slice Zone field in *Rent Residential*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rent_residential.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RentResidentialDocumentDataSlicesSlice> /**
   * Meta Title field in *Rent Residential*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: rent_residential.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Rent Residential*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: rent_residential.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Rent Residential*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rent_residential.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Rent Residential document from Prismic
 *
 * - **API ID**: `rent_residential`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RentResidentialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RentResidentialDocumentData>,
    "rent_residential",
    Lang
  >;

export type AllDocumentTypes =
  | BlogPostDocument
  | BuycommercialDocument
  | BuyresidentialDocument
  | HomepageDocument
  | NewsDocument
  | PageDocument
  | PropertyDocument
  | RentCommercialDocument
  | RentResidentialDocument;

/**
 * Primary content in *BlogIndex → Default → Primary*
 */
export interface BlogIndexSliceDefaultPrimary {
  /**
   * Heading field in *BlogIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *BlogIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for BlogIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogIndexSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogIndex*
 */
type BlogIndexSliceVariation = BlogIndexSliceDefault;

/**
 * BlogIndex Shared Slice
 *
 * - **API ID**: `blog_index`
 * - **Description**: BlogIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogIndexSlice = prismic.SharedSlice<
  "blog_index",
  BlogIndexSliceVariation
>;

/**
 * Item in *Connect → Default → Primary → Images*
 */
export interface ConnectSliceDefaultPrimaryImagesItem {
  /**
   * Office Image field in *Connect → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: connect.default.primary.images[].office_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  office_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Connect → Default → Primary*
 */
export interface ConnectSliceDefaultPrimary {
  /**
   * Heading field in *Connect → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: connect.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Connect → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: connect.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Images field in *Connect → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: connect.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<ConnectSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for Connect Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConnectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConnectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Connect*
 */
type ConnectSliceVariation = ConnectSliceDefault;

/**
 * Connect Shared Slice
 *
 * - **API ID**: `connect`
 * - **Description**: Connect
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConnectSlice = prismic.SharedSlice<
  "connect",
  ConnectSliceVariation
>;

/**
 * Primary content in *ContactFormSlice → Default → Primary*
 */
export interface ContactFormSliceSliceDefaultPrimary {
  /**
   * Heading field in *ContactFormSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ContactFormSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Sub Heading field in *ContactFormSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;
}

/**
 * Default variation for ContactFormSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactFormSlice*
 */
type ContactFormSliceSliceVariation = ContactFormSliceSliceDefault;

/**
 * ContactFormSlice Shared Slice
 *
 * - **API ID**: `contact_form_slice`
 * - **Description**: ContactFormSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceSlice = prismic.SharedSlice<
  "contact_form_slice",
  ContactFormSliceSliceVariation
>;

/**
 * Item in *FeaturedEstates → Default → Primary → Estate*
 */
export interface FeaturedEstatesSliceDefaultPrimaryEstateItem {
  /**
   * Title field in *FeaturedEstates → Default → Primary → Estate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_estates.default.primary.estate[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Tag field in *FeaturedEstates → Default → Primary → Estate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_estates.default.primary.estate[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Bed field in *FeaturedEstates → Default → Primary → Estate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_estates.default.primary.estate[].bed
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bed: prismic.KeyTextField;

  /**
   * Bath field in *FeaturedEstates → Default → Primary → Estate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_estates.default.primary.estate[].bath
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bath: prismic.KeyTextField;

  /**
   * Square FT field in *FeaturedEstates → Default → Primary → Estate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_estates.default.primary.estate[].square_ft
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  square_ft: prismic.KeyTextField;

  /**
   * Estate Image field in *FeaturedEstates → Default → Primary → Estate*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_estates.default.primary.estate[].estate_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  estate_image: prismic.ImageField<never>;
}

/**
 * Primary content in *FeaturedEstates → Default → Primary*
 */
export interface FeaturedEstatesSliceDefaultPrimary {
  /**
   * Heading field in *FeaturedEstates → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_estates.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *FeaturedEstates → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_estates.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Estate field in *FeaturedEstates → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_estates.default.primary.estate[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  estate: prismic.GroupField<
    Simplify<FeaturedEstatesSliceDefaultPrimaryEstateItem>
  >;
}

/**
 * Default variation for FeaturedEstates Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedEstatesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedEstatesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedEstates*
 */
type FeaturedEstatesSliceVariation = FeaturedEstatesSliceDefault;

/**
 * FeaturedEstates Shared Slice
 *
 * - **API ID**: `featured_estates`
 * - **Description**: FeaturedEstates
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedEstatesSlice = prismic.SharedSlice<
  "featured_estates",
  FeaturedEstatesSliceVariation
>;

/**
 * Default variation for FollowUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FollowUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FollowUs*
 */
type FollowUsSliceVariation = FollowUsSliceDefault;

/**
 * FollowUs Shared Slice
 *
 * - **API ID**: `follow_us`
 * - **Description**: FollowUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FollowUsSlice = prismic.SharedSlice<
  "follow_us",
  FollowUsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Highlight → Default → Primary*
 */
export interface HighlightSliceDefaultPrimary {
  /**
   * Featured Image field in *Highlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.default.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Heading field in *Highlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Highlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Content field in *Highlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Highlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HighlightSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Highlight → Background with Heading → Primary*
 */
export interface HighlightSliceBackgroundWithHeadingPrimary {
  /**
   * Featured Image field in *Highlight → Background with Heading → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.backgroundWithHeading.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Heading field in *Highlight → Background with Heading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.backgroundWithHeading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Highlight → Background with Heading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.backgroundWithHeading.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Content field in *Highlight → Background with Heading → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.backgroundWithHeading.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Background with Heading variation for Highlight Slice
 *
 * - **API ID**: `backgroundWithHeading`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceBackgroundWithHeading = prismic.SharedSliceVariation<
  "backgroundWithHeading",
  Simplify<HighlightSliceBackgroundWithHeadingPrimary>,
  never
>;

/**
 * Slice variation for *Highlight*
 */
type HighlightSliceVariation =
  | HighlightSliceDefault
  | HighlightSliceBackgroundWithHeading;

/**
 * Highlight Shared Slice
 *
 * - **API ID**: `highlight`
 * - **Description**: Highlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSlice = prismic.SharedSlice<
  "highlight",
  HighlightSliceVariation
>;

/**
 * Primary content in *ListingIndex → Default → Primary*
 */
export interface ListingIndexSliceDefaultPrimary {
  /**
   * Listing Type field in *ListingIndex → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: listing_index.default.primary.listing_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  listing_type: prismic.SelectField<"Buy" | "Rent">;

  /**
   * Property Type field in *ListingIndex → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: listing_index.default.primary.property_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  property_type: prismic.SelectField<"Residential " | "Commercial">;
}

/**
 * Default variation for ListingIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListingIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ListingIndexSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ListingIndex*
 */
type ListingIndexSliceVariation = ListingIndexSliceDefault;

/**
 * ListingIndex Shared Slice
 *
 * - **API ID**: `listing_index`
 * - **Description**: ListingIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListingIndexSlice = prismic.SharedSlice<
  "listing_index",
  ListingIndexSliceVariation
>;

/**
 * Primary content in *NewsIndex → Default → Primary*
 */
export interface NewsIndexSliceDefaultPrimary {
  /**
   * Heading field in *NewsIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_index.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *NewsIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_index.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for NewsIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsIndexSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsIndex*
 */
type NewsIndexSliceVariation = NewsIndexSliceDefault;

/**
 * NewsIndex Shared Slice
 *
 * - **API ID**: `news_index`
 * - **Description**: NewsIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsIndexSlice = prismic.SharedSlice<
  "news_index",
  NewsIndexSliceVariation
>;

/**
 * Item in *OurTeam → Default → Primary → members*
 */
export interface OurTeamSliceDefaultPrimaryMembersItem {
  /**
   * First Name field in *OurTeam → Default → Primary → members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.members[].first_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_name: prismic.KeyTextField;

  /**
   * Last Name field in *OurTeam → Default → Primary → members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.members[].last_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  last_name: prismic.KeyTextField;

  /**
   * Designation field in *OurTeam → Default → Primary → members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.members[].designation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  designation: prismic.KeyTextField;

  /**
   * Member Image field in *OurTeam → Default → Primary → members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.members[].member_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  member_image: prismic.ImageField<never>;
}

/**
 * Primary content in *OurTeam → Default → Primary*
 */
export interface OurTeamSliceDefaultPrimary {
  /**
   * Heading field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * members field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  members: prismic.GroupField<Simplify<OurTeamSliceDefaultPrimaryMembersItem>>;
}

/**
 * Default variation for OurTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurTeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurTeam*
 */
type OurTeamSliceVariation = OurTeamSliceDefault;

/**
 * OurTeam Shared Slice
 *
 * - **API ID**: `our_team`
 * - **Description**: OurTeam
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurTeamSlice = prismic.SharedSlice<
  "our_team",
  OurTeamSliceVariation
>;

/**
 * Primary content in *Partners → Default → Primary*
 */
export interface PartnersSliceDefaultPrimary {
  /**
   * Heading field in *Partners → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Default variation for Partners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Partners*
 */
type PartnersSliceVariation = PartnersSliceDefault;

/**
 * Partners Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSlice = prismic.SharedSlice<
  "partners",
  PartnersSliceVariation
>;

/**
 * Primary content in *ProductInfo → Default → Primary*
 */
export interface ProductInfoSliceDefaultPrimary {
  /**
   * Product Image field in *ProductInfo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_info.default.primary.product_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Title field in *ProductInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_info.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Price field in *ProductInfo → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_info.default.primary.price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;
}

/**
 * Default variation for ProductInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductInfo*
 */
type ProductInfoSliceVariation = ProductInfoSliceDefault;

/**
 * ProductInfo Shared Slice
 *
 * - **API ID**: `product_info`
 * - **Description**: ProductInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductInfoSlice = prismic.SharedSlice<
  "product_info",
  ProductInfoSliceVariation
>;

/**
 * Item in *Properties → Default → Primary → Property Cards*
 */
export interface PropertiesSliceDefaultPrimaryPropertyCardsItem {
  /**
   * Card Image field in *Properties → Default → Primary → Property Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.default.primary.property_cards[].card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Card Heading field in *Properties → Default → Primary → Property Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.default.primary.property_cards[].card_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_heading: prismic.KeyTextField;
}

/**
 * Primary content in *Properties → Default → Primary*
 */
export interface PropertiesSliceDefaultPrimary {
  /**
   * Heading field in *Properties → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Properties → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Property Cards field in *Properties → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.default.primary.property_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  property_cards: prismic.GroupField<
    Simplify<PropertiesSliceDefaultPrimaryPropertyCardsItem>
  >;
}

/**
 * Default variation for Properties Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PropertiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PropertiesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Properties*
 */
type PropertiesSliceVariation = PropertiesSliceDefault;

/**
 * Properties Shared Slice
 *
 * - **API ID**: `properties`
 * - **Description**: Properties
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PropertiesSlice = prismic.SharedSlice<
  "properties",
  PropertiesSliceVariation
>;

/**
 * Default variation for StatsSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *StatsSlice*
 */
type StatsSliceSliceVariation = StatsSliceSliceDefault;

/**
 * StatsSlice Shared Slice
 *
 * - **API ID**: `stats_slice`
 * - **Description**: StatsSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsSliceSlice = prismic.SharedSlice<
  "stats_slice",
  StatsSliceSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Client Testimonial*
 */
export interface TestimonialsSliceDefaultPrimaryClientTestimonialItem {
  /**
   * Name field in *Testimonials → Default → Primary → Client Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.client_testimonial[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * content field in *Testimonials → Default → Primary → Client Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.client_testimonial[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Client Testimonial field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.client_testimonial[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  client_testimonial: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryClientTestimonialItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * TextBlock field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.textblock
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textblock: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BuycommercialDocument,
      BuycommercialDocumentData,
      BuycommercialDocumentDataSlicesSlice,
      BuyresidentialDocument,
      BuyresidentialDocumentData,
      BuyresidentialDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      NewsDocument,
      NewsDocumentData,
      NewsDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PropertyDocument,
      PropertyDocumentData,
      PropertyDocumentDataSlicesSlice,
      RentCommercialDocument,
      RentCommercialDocumentData,
      RentCommercialDocumentDataSlicesSlice,
      RentResidentialDocument,
      RentResidentialDocumentData,
      RentResidentialDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogIndexSlice,
      BlogIndexSliceDefaultPrimary,
      BlogIndexSliceVariation,
      BlogIndexSliceDefault,
      ConnectSlice,
      ConnectSliceDefaultPrimaryImagesItem,
      ConnectSliceDefaultPrimary,
      ConnectSliceVariation,
      ConnectSliceDefault,
      ContactFormSliceSlice,
      ContactFormSliceSliceDefaultPrimary,
      ContactFormSliceSliceVariation,
      ContactFormSliceSliceDefault,
      FeaturedEstatesSlice,
      FeaturedEstatesSliceDefaultPrimaryEstateItem,
      FeaturedEstatesSliceDefaultPrimary,
      FeaturedEstatesSliceVariation,
      FeaturedEstatesSliceDefault,
      FollowUsSlice,
      FollowUsSliceVariation,
      FollowUsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HighlightSlice,
      HighlightSliceDefaultPrimary,
      HighlightSliceBackgroundWithHeadingPrimary,
      HighlightSliceVariation,
      HighlightSliceDefault,
      HighlightSliceBackgroundWithHeading,
      ListingIndexSlice,
      ListingIndexSliceDefaultPrimary,
      ListingIndexSliceVariation,
      ListingIndexSliceDefault,
      NewsIndexSlice,
      NewsIndexSliceDefaultPrimary,
      NewsIndexSliceVariation,
      NewsIndexSliceDefault,
      OurTeamSlice,
      OurTeamSliceDefaultPrimaryMembersItem,
      OurTeamSliceDefaultPrimary,
      OurTeamSliceVariation,
      OurTeamSliceDefault,
      PartnersSlice,
      PartnersSliceDefaultPrimary,
      PartnersSliceVariation,
      PartnersSliceDefault,
      ProductInfoSlice,
      ProductInfoSliceDefaultPrimary,
      ProductInfoSliceVariation,
      ProductInfoSliceDefault,
      PropertiesSlice,
      PropertiesSliceDefaultPrimaryPropertyCardsItem,
      PropertiesSliceDefaultPrimary,
      PropertiesSliceVariation,
      PropertiesSliceDefault,
      StatsSliceSlice,
      StatsSliceSliceVariation,
      StatsSliceSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryClientTestimonialItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
