// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_index: dynamic(() => import("./BlogIndex")),
  connect: dynamic(() => import("./Connect")),
  follow_us: dynamic(() => import("./FollowUs")),
  hero: dynamic(() => import("./Hero")),
  highlight: dynamic(() => import("./Highlight")),
  partners: dynamic(() => import("./Partners")),
  product_info: dynamic(() => import("./ProductInfo")),
  properties: dynamic(() => import("./Properties")),
  testimonials: dynamic(() => import("./Testimonials")),
};
