// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_index: dynamic(() => import("./BlogIndex")),
  connect: dynamic(() => import("./Connect")),
  contact_form_slice: dynamic(() => import("./ContactFormSlice")),
  featured_estates: dynamic(() => import("./FeaturedEstates")),
  follow_us: dynamic(() => import("./FollowUs")),
  hero: dynamic(() => import("./Hero")),
  highlight: dynamic(() => import("./Highlight")),
  listing_index: dynamic(() => import("./ListingIndex")),
  news_index: dynamic(() => import("./NewsIndex")),
  our_team: dynamic(() => import("./OurTeam")),
  partners: dynamic(() => import("./Partners")),
  product_info: dynamic(() => import("./ProductInfo")),
  properties: dynamic(() => import("./Properties")),
  stats_slice: dynamic(() => import("./StatsSlice")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_block: dynamic(() => import("./TextBlock")),
};
